### ISSUE TITLE
Pull images from NPS Focus

### ISSUE THREAD

**Issue by heyyeyheman** [nationalparkservice/npmap-species#10]
Once images are stored on GitHub, need to modify points in the code which reference the images to pull from there (currently a single Fraser Fir image is used).

**Comment by tpcolson** [comment]
Ummmmm.....@Kendra, how can/will the images thing work if we, for some reason, can't put them in GH? Won't we blow past the 1 GB limit? What about NPFocus?

**Comment by KendraStraub** [comment]
@tpcolson I am not sure why this is assigned to me. The original issue states that code needs to be edited to pull in photos. 

We can talk about this in our next UT/MaxEnt meeting. NPS Focus is a metadata repository and image server. We could use NPS Focus but would still need UT to provide a workflow and of course all the code required.

**Comment by tpcolson** [comment]
jduggan1, what would you need from us, if we were to store these photos on NPFocus? http://focus.nps.gov/

**Comment by jduggan1** [comment]
The only thing I should need is a consistent naming convention for the images, so that I can know how to turn each species name/id into a usable image link.  When you upload files to that server, can you specify the name or id of the file?

**Comment by KendraStraub** [comment]
Hi John, 
Yes, we will be able to predict the naming convention of the URLs/IDs for each image. I will speak with the NPSFocus people and outline the specifics. 
Thanks!

**Comment by KendraStraub** [comment]
@jduggan1  AND @tpcolson  -- 

We are now using Flickr. We will have a URL per species. The URL can be provided as part of the extract in the future, but currently, we do not have a field to store the URL in. NPSpecies (where our observations will be stored) is in the process of adding the field for us. 

We may want to plan ahead for this eventuality. Perhaps integrate the field into the code even though the field is not yet populated.

**Comment by tpcolson** [comment]
Flickr not NPFocus

**Comment by KendraStraub** [comment]
URL will be a part of the extract in the near future. As long as the code is ready to point to that URL, the images do not need to be 'pulled' from anywhere.
