### ISSUE TITLE
Confirm that https can be enabled

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#100]
Confirm that https can be enabled...or enabling https won't break things. But do not make any changes to production yet.

**Comment by jduggan1** [comment]
Contrary to my expectations, I was not able to use https as the fullscreen template css from nps.gov cannot be pulled over https.

**Comment by jduggan1** [comment]
On this note, can we close this issue or do we need to leave it open for the time being?

**Comment by tpcolson** [comment]
Leave open. This may or may not be an  issue when we move to NPS web server, or, once there, will no longer be an issue.

**Comment by jduggan1** [comment]
Good news. I tried it again today and everything worked fine getting loaded over https, so the page now loads successfully with https (and shouldn't be using any http URLs anymore).
