### ISSUE TITLE
Drop-down menus cover eachother

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#108]
When selecting "Select Map Overlays", if a map overlay is not select, and "Select Map Background" is activated, the Map Overlays drop-down is still activated and the Map Background dropdown merges with it, making it difficult to use. 

![image](https://cloud.githubusercontent.com/assets/5861784/14722766/3acd5c44-07db-11e6-8725-9a0a29e7a289.png)

**Comment by tpcolson** [comment]
...all drop-downs do this.....

**Comment by jduggan1** [comment]
Should be fixed with https://github.com/nationalparkservice/npmap-species/commit/da1da2c85ff383417c0b9d7d286d4975ead2a56d
