### ISSUE TITLE
White box when scrolling to far right

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#109]
when scrolling to far right, a white box appears....

![image](https://cloud.githubusercontent.com/assets/5861784/14958991/519dc728-105b-11e6-9ce8-1c775b428944.png)

**Comment by jduggan1** [comment]
Should be fixed with https://github.com/nationalparkservice/npmap-species/commit/4eab84975a4953ff942151511e41920e1e1a6aab
