### ISSUE TITLE
Different Shades of Grey

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#110]
Where picture surround used to be

![image](https://cloud.githubusercontent.com/assets/5861784/14959030/805a7610-105b-11e6-90ca-63cd1c85453e.png)

**Comment by jduggan1** [comment]
Also, need to remove the no_image.png as a part of this.

**Comment by jduggan1** [comment]
I don't seem to be able to reproduce this anymore after completely removing the space for the image from the page. I'll leave this open until I check with you tomorrow, but it seems to be fixed.
