### ISSUE TITLE
Some MB Tiles are being 404'ed

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#118]
When initial load of a species, and/or zooming and panning, some MB tiles are being 404'ed. However, there appear to be no missing tiles when viewing the map. 

![image](https://cloud.githubusercontent.com/assets/5861784/15426836/1d392524-1e5f-11e6-9a36-110fcbea736e.png)

@nateirwin ?

**Comment by nateirwin** [comment]
This probably isn't an issue. This will happen if a Mapbox tile source is limited by max/min zoom and/or a bounding box, but the map is trying to pull tiles for areas that aren't cached.

If you're seeing what you expect on the map, you can safely ignore this.
