### ISSUE TITLE
Option to Filter by Edibility

### ISSUE THREAD

**Issue by josborn8** [nationalparkservice/npmap-species#124]
It would be quite convenient if I could filter species by edibility.

**Comment by pwerner2** [comment]
LOL, nice. Seconded. Pairing options would be good as well. For seconds.

**Comment by tpcolson** [comment]
We've put this in the development que. Having a weekly Agile Sprint on this topic. After the first Sprint, we also decided to add "tastes like" to the grouping matrix.

**Comment by KendraStraub** [comment]
We will be tackling grouping in next phase. Closing this.
