### ISSUE TITLE
Add GA Event Tracking

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#126]
Add GA Event Tracking to all events (menu pull-down, button click, etc) IAW https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide#setting-up-event-tracking

**Comment by tpcolson** [comment]
Downloaded the latest from GH and deployed to test server. Site initially loads, but upon "Select a Species" and select any species, returns following error: 

Uncaught ReferenceError: label is not defined
    at recordAction (http://imtest/parks/grsm/species/utils.js:408:45)
    at selectInitialSpecies (http://imtest/parks/grsm/species/searchUtils.js:345:3)
    at HTMLLIElement.li.onclick.li.onkeypress (http://imtest/parks/grsm/species/searchUtils.js:189:9)

Restoring original code back to test server eliminated the error, so browser or server issues have been ruled out.

**Comment by jduggan1** [comment]
Well that was embarrassing. I somehow failed to copy over the new function header when sending the ga event. Should be fixed now, if not let me know.

**Comment by tpcolson** [comment]
Trying to figure out if it's working....can you comment before the lines where an event action is "recorded"?

**Comment by jduggan1** [comment]
I've added a console log that should get written out immediately before the event is sent to GA, showing the event and a label if one exists (typically I just used species names for the labels).

**Comment by tpcolson** [comment]
wow. very cool. I think something's not connecting with the Google Analytics site: Not getting any activity under the "Events" section. Are you able to reproduce with your own GA tracking code?

**Comment by jduggan1** [comment]
I was looking at it on your page, and it appears to be sending messages to GA with the correct information (this is from looking at the network tab in the developer tools for Chrome). I would guess one of two things is happening:

1. It's operating correctly, but GA has a delay before it reports the events back to you through the dashboard.
2. Your access token for GA is incorrect, it's pointing to the wrong account, or something along these lines.

**Comment by tpcolson** [comment]
It's working now. takes 24 hours for events to send messages to GA
