### ISSUE TITLE
Add GRSM Nature link to Species Mapper Header

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#128]
We would like to add a link to the species mapper header. The 'Great Smoky Mountains National Park' should be a link to the following:

https://www.nps.gov/grsm/learn/nature/index.htm

![image](https://cloud.githubusercontent.com/assets/8036575/16765554/bb8cb6d8-4802-11e6-9f5e-297f181f6c62.png)

**Comment by tpcolson** [comment]
Done
