### ISSUE TITLE
Make 'Compare with...' Text Clickable

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#129]
Comment from reviewer, Paul Super, GRSM research coordinator (note: similar feedback came from our Resource Education reviewer):

"I see what the problem is with the compare.  I kept trying to click on the words, which did nothing, and I expected to see the cursor change as I went over whatever the hotspot was and it changes to an arrow, rather than a click finger, when I go over the bullet so I did not interpret that as meaning the bullet was the link.  Seems to me that this is not using conventions and hard to figure out."

**Comment by tpcolson** [comment]
update text so when clicked will populate radio button

**Comment by KendraStraub** [comment]
This issue was also noted by several of the teachers reviewing this application.

**Comment by KendraStraub** [comment]
When text is clicked, radio button is populated in new version. This can be closed.
