### ISSUE TITLE
Fix top-right button locations

### ISSUE THREAD

**Issue by jduggan1** [nationalparkservice/npmap-species#13]
Buttons in the top-right menu get pushed down 10px.  Need to investigate and fix.

**Comment by KendraStraub** [comment]
I'm not sure if this is the same issue or not... But I noticed that the pop-in/pop-out button on the top right obstructs the close button for the black accordion.

**Comment by jduggan1** [comment]
Yep it's the same issue.  I just pushed a patch for this to the repo.  If you are still noticing problems please open a new issue. :-)
