### ISSUE TITLE
'Common' vs 'Latin' toggle button: Confusion

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#130]
Comment from reviewer, Paul Super, GRSM research coordinator:

" the toggle bar for "Common" vs "Latin" I took to mean that the species I selected was common.  It would be helpful if this had above it "search by" and maybe the toggle bar said "common name" and "latin name".  Don't know if you have any control over that, but it took me a long time to figure out that that was how one searched by scientific name, and then I found it only because I could not believe you did not have such an option.  I do see the instructions balloon up if one hovers over the toggle, but I would not have thought to hover over it, not seeing that it was indeed a toggle bar."

**Comment by KendraStraub** [comment]
This issue was brought up several times by teachers reviewing this application.

**Comment by auxiliary** [comment]
This has been fixed in the latest version and will be pushed in the near future along with the other changes.

**Comment by KendraStraub** [comment]
This can be closed. It is a radio button in the new version.
