### ISSUE TITLE
SPECIES WITH SIMILAR DISTRIBUTION list ordering

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#143]
How is the species list in the SPECIES WITH SIMILAR DISTRIBUTION list ordered? It is not alphabetical-- a couple of teachers asked if it was listed from most similar to least similar.

**Comment by auxiliary** [comment]
They guessed correctly. They are ordered based on how similar the distributions are, from most similar to least. Also, the number of the elements in the list is capped at 15 at the moment.
