### ISSUE TITLE
Share Tool: Weird behavior

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#148]
On the new share tool, after creating a map and hitting the share button, hitting the "back" arrow in the browser to go to previous page, the species that was selected when the share was made, persists. Hitting the browser previous page button should clear all states.

**Comment by auxiliary** [comment]
The problem was that the browser's URL changed although the page didn't refresh and that was confusing. In reality, there is no previous page to go back to. A better behavior is implemented in merge #149.
