### ISSUE TITLE
Update site repo automatically

### ISSUE THREAD

**Issue by jduggan1** [nationalparkservice/npmap-species#16]
Due to GitHub API constraint, I have had to switch to keeping a local copy of the repo.  Need to keep this in sync.  A cron job should be sufficient for our side, need to investigate something similar for the Denver server.

**Comment by jduggan1** [comment]
@tpcolson: The following command will need to be run on the Denver server in order to keep the site updated:

`schtasks /Create /SC HOURLY /TN PythonTask /TR "python updateRepo.py"`

Whoever runs this will need to modify the updateRepo.py part to point to the path pointing to the updateRepo.py command.

**Comment by tpcolson** [comment]
This will need further explanation.....? (In non-technical terms).

**Comment by jduggan1** [comment]
Sorry, I will try to explain better!  Some of the data needed by the site is stored in this repo, and GitHub prevents us from pulling that data directly into the site.

In order to fix this, I am storing a local copy of this repo on the server and pulling the needed data from there.  To keep this local copy updated, the above script would check for updates to our repo once per hour.

**Comment by nateirwin** [comment]
If GitHub Pages is enabled, and it looks like it is, you can wrap any GeoJSON stored in a callback (e.g. JSONP). I don't know which file you are looking to load, but if you're loading from a static server, GeoJSON should work fine.

**Comment by jduggan1** [comment]
With this, I wouldn't need to worry about GitHub's rate limits?  I would be much happier forgetting this and just pulling directly from GitHub if possible. :-)

**Comment by tpcolson** [comment]
I thought we solved that when Nate enabled the GitHub IO thingy (GH Pages).

**Comment by nateirwin** [comment]
If you pull from GitHub Pages, there is no rate limit. Just make sure you load from the http://nationalparkservice.github.io/npmap-species/ URL.

**Comment by jduggan1** [comment]
Thanks for the input, Nate!  I've updated the site to make use of this.
