### ISSUE TITLE
No pop up when click observation

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#162]
When I click on an observation in species mapper, there is no pop up with observation information. I am using Chrome.

**Comment by KendraStraub** [comment]
after testing a few randomly- appears this is an issue with all species.

**Comment by tpcolson** [comment]
Bump. Can repro in multiple browsers. The vector overlay pop ups are not working either (campsites, campgrounds, etc...)

**Comment by tpcolson** [comment]
@jakecoolidge @jimmyrocks @yetiracing4als could this be similar to the CMS issue I submitted today as well?

**Comment by auxiliary** [comment]
I think this is fixed in the new version.

**Comment by KendraStraub** [comment]
Pop ups are now functioning as expected.
