### ISSUE TITLE
Add American chestnut as species selection option

### ISSUE THREAD

**Issue by sjobowers** [nationalparkservice/npmap-species#165]
Ticket # 151 says 'species will be added as data is acquired. No special action required.' How is data acquired? Can we, The American Chestnut Foundation, submit our database points of wild _Castanea dentata_ to assist? Integrate University of Kentucky 's TreeSnap app datapoints?

**Comment by KendraStraub** [comment]
@sjobowers - we would be happy to receive data from The American Chestnut Foundation. We receive data from dozens of permitted studies each year. We process these data for this project and other purposes. Please feel free to email me and we can chat more about it: kendra_straub@nps.gov. 

Also, if you don't already have a permit for your work within the park, you can apply here: https://irma.nps.gov/rprs/

Thank you for your interest

**Comment by sjobowers** [comment]
Thanks, we have a permit. We will be in touch. Thank you for the prompt reply.
