### ISSUE TITLE
Roads Layer no longer loads

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#18]
Roads Layer no longer loads due to a snafu with ArcGIS.Com. Colson needs to provide new link to GeoJSON

**Comment by tpcolson** [comment]
ESRI changed the link on us. Roads Geojson should now be http://services1.arcgis.com/fBc8EJBxQRMcHlei/arcgis/rest/services/GRSM_ROAD_CENTERLINES/FeatureServer/0/query?f=geojson&outSR=4326&where=OBJECTID%20IS%20NOT%20NULL&outFields=*

**Comment by jduggan1** [comment]
I've updated it. I'll close this one, please open a new one if they change it again.
