### ISSUE TITLE
Add park boundary geojson

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#19]
Add park boundary geojson as a line

**Comment by tpcolson** [comment]
and here is the link to the GeoJSON

http://services1.arcgis.com/fBc8EJBxQRMcHlei/arcgis/rest/services/Great_Smoky_Mountains_National_Park_Boundary/FeatureServer/0/query?f=geojson&outSR=4326&where=OBJECTID%20IS%20NOT%20NULL&outFields=*

**Comment by jduggan1** [comment]
Added. I've made it irremovable; please let me know if this isn't the correct behavior.
