### ISSUE TITLE
Add pop-up to "Full Screen Button"

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#20]
Add pop-up to "Full Screen Button" on mouse-over that clarifies what full screen is, and why it is needed.

**Comment by tpcolson** [comment]
![image](https://cloud.githubusercontent.com/assets/5861784/8081928/2f8a278c-0f47-11e5-95b9-a3f0dd0d9d44.png)

**Comment by jduggan1** [comment]
Added a simple tooltip to the button. If you like it, I'll let you close this issue. :-)
