### ISSUE TITLE
Remove color legend from landing page

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#21]
Remove color legend from landing page. When site is first viewed, color legend pops up...is confusing why it is there in the "little screen" initial view? Better if color legend only shows AFTER a search has been done?

**Comment by tpcolson** [comment]
![image](https://cloud.githubusercontent.com/assets/5861784/8081882/ac30087a-0f46-11e5-854a-c0ce383c97d6.png)

**Comment by KendraStraub** [comment]
I agree. The legend is large and out of place when there are no results on the map to interpret.

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
