### ISSUE TITLE
View Observed Sightings

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#22]
When full screen view is first activated, the "View Observed Sightings" checkbox is enabled. Checking it on or off...does nothing. Check box should be greyed out unless there are search results to actually show.

**Comment by jduggan1** [comment]
Sarah, what is your opinion on this?

**Comment by tpcolson** [comment]
Bump

**Comment by jduggan1** [comment]
Checkboxes are now disabled if no species are being shown.
