### ISSUE TITLE
Visitor Centers

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#23]
VC Layer is in-op. Colson needs to provide link.

**Comment by tpcolson** [comment]
http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_VISITOR_CENTERS/FeatureServer/0/query?f=geojson&outSR=4326&where=OBJECTID%20IS%20NOT%20NULL&outFields=*

**Comment by jduggan1** [comment]
Thanks!
