### ISSUE TITLE
BC Campsites 

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#24]
BC Campsites layer is inop. Colson needs to provide link.

**Comment by jduggan1** [comment]
Out of curiosity, how often do these links change? The roads and trails have remained valid since I added them a while back, but the others have all changed (it seems like they have done so fairly recently).

**Comment by tpcolson** [comment]
THese "shouldn't" be changing. 

http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_BACKCOUNTRY_CAMPSITES/FeatureServer/0/query?f=geojson&outSR=4326&where=OBJECTID%20IS%20NOT%20NULL&outFields=*

**Comment by jduggan1** [comment]
Thanks.  If I notice the links break I'll open a new issue. :-)
