### ISSUE TITLE
Shelters pop-up is blank

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#25]
When clicking on a shelter icon, the shelter name should be in the pop up.

**Comment by tpcolson** [comment]
Shelter name should also appear during mouse over.

**Comment by tpcolson** [comment]
![image](https://cloud.githubusercontent.com/assets/5861784/8081959/75c908b2-0f47-11e5-83e4-b34e919e332b.png)

**Comment by tpcolson** [comment]
Upon further investigation, the text is offset (and white) outside of the pop up window....

**Comment by jduggan1** [comment]
This is the same problem as the trail popup. I've marked this as a duplicate and will follow up as soon as I can.

**Comment by jduggan1** [comment]
Fixed.
