### ISSUE TITLE
Trail pop up is blank

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#26]
When a trail is clicked on, the trail name should appear in the pop up, as well as during mouse over event.

**Comment by tpcolson** [comment]
Upon further investigation, the text is offset (and white) outside of the pop up window....

**Comment by tpcolson** [comment]
![image](https://cloud.githubusercontent.com/assets/5861784/8081984/b5139a50-0f47-11e5-9cc4-286165d346ef.png)

**Comment by jduggan1** [comment]
This one is very bizarre (it's happening on all of these). I've taken a look at it but don't understand why it's doing it yet. I will give you an update when I figure it out.

**Comment by jduggan1** [comment]
Fixed.
