### ISSUE TITLE
What is a pixel?

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#27]
Given our audience, a pop up should be on the "Current View" label to explain what a pixel is, and how scale and zoom level are configured/work for this site.

**Comment by tpcolson** [comment]
![image](https://cloud.githubusercontent.com/assets/5861784/8082025/0b85f216-0f48-11e5-8ec6-dd05e9fbee61.png)

**Comment by jduggan1** [comment]
Good point, I'll add a tooltip to that section. I'll create a first draft explanation and we can see what the early testers think of it.

**Comment by jduggan1** [comment]
Actually, I've been giving this some thought, and I think it would make more sense to give the width and height of the map instead (it would say 10km by 4km). However, this is an issue for Sarah, so I'll bring her into this conversation tomorrow.

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
