### ISSUE TITLE
Annotate Map doesn't work

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#29]
Annotate Map doesn't work. Also, given our audience, a less techincal term than annotate?

**Comment by jduggan1** [comment]
This one has been on my radar for a while, I will try to tackle it next weekend as it's a larger change for me to make. Also, I've got my own issue for this one already created so I've marked this as a duplicate (I'll close this one when I finish the other one).

**Comment by jduggan1** [comment]
Finally got it to work in our toolbar.  I'm going to open a new issue regarding the wording of the control.
