### ISSUE TITLE
Develop metadata for environmental layers

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#3]
Need to develop metadata for environmental layers which allows researchers and users to easily understand the "contribution" that layer has on Maxent output.

**Comment by KendraStraub** [comment]
@tpcolson -- Can you provide more explanation on this one?

**Comment by tpcolson** [comment]
Each env. layer needs FGDC  metadata and an IRMA link

**Comment by auxiliary** [comment]
This is fixed by the EnviroMapper project. Please re-open if I misunderstood.
