### ISSUE TITLE
Search results extent

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#30]
Upon executing a search of single species, the map should auto zoom to the extent of that species distro raster.

**Comment by KendraStraub** [comment]
Agreed, You can see in the image below that some distributions are small enough that a user may assume that the search functionality did not work because it is very difficult to discern the difference in shading. 
![9](https://cloud.githubusercontent.com/assets/8036575/8084559/9f95d7c6-0f59-11e5-85fb-907c121de45c.PNG)

**Comment by jduggan1** [comment]
That is not something I can do with mapbox. I just get a set of images to display, but the contents are unknown.  I can talk to Lonnie about other ways to do this, but it will take a decent amount of time to produce anything useful.

**Comment by lonnieljyu** [comment]
We can zoom to a given extent for each species. However, the extent will need to be given to us, like in the ATBI extracts file.

**Comment by tpcolson** [comment]
Can we set the default extent for everything to be the same, the park bounding-box footprint?

**Comment by lonnieljyu** [comment]
Yes, we can set a default extent. The current default extent is the one sent to me by @tpcolson,
"xmin, ymin: -83.94809, 35.43223 xmax, ymax: -83.0404, 35.78799"

**Comment by jduggan1** [comment]
The default extent I use on the site fits the park boundaries on the non-fullscreen page. Also, Lonnie, I don't have the ability to zoom in that manner (I can only use zoom level/center, which doesn't give us as much control).

I think if we want to come up with a solution that actually solves this problem it's not going to be easy, as we would need to produce a zoom level/center at the time the species models are generated on the supercomputer, and I doubt this is going to be worth our time in the next few weeks with other activities taking priority.

**Comment by lonnieljyu** [comment]
Thanks for the info, @jduggan1. Unless @tpcolson can provide us the centers for each species map, it wouldn't be worth the effort in this phase of development to calculate them.

**Comment by KendraStraub** [comment]
@tpcolson  and @jduggan1  -- Can we close this? 

Seems like we cannot zoom to distribution extent and seem to already have a default zoom.
