### ISSUE TITLE
Cannot return to single species search

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#32]
After performing any of the advanced search and analyis functions, cannot return to just show a single species function.

**Comment by jduggan1** [comment]
I don't fully understand, do you mean you can't return to the original search page or you can't clear all but the species from the initial search?

**Comment by jduggan1** [comment]
Nevermind, I was busy reading the comment and didn't see the title. You can do that with the breadcrumb (hit the "SEARCH" portion of it).  Do we need a clear way to indicate this to the user?

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
