### ISSUE TITLE
Species persist between search types

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#34]
When selecting a single species in first screen/search/single species display, then choosing other search types (environment, distro), the other 2 (or more) species selected persist. When moving between search types, only the first species selected in the original species search should persist.

**Comment by jduggan1** [comment]
Can you provide some screenshots or something similar? I'm not able to reproduce it from the description alone.

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
