### ISSUE TITLE
Using keyboard to search by name only works for common

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#38]
when searching by species, using the keyboard to type first few letters only resolves to common name. The correct behavior should work for common and latin name....

**Comment by tpcolson** [comment]
![image](https://cloud.githubusercontent.com/assets/5861784/8081297/a1595e9c-0f41-11e5-8713-364672c2759d.png)

**Comment by KendraStraub** [comment]
I found the same issue. It is unclear why some of the results show up. When you type in a series of letters, seemingly unrelated species show up. 
![3](https://cloud.githubusercontent.com/assets/8036575/8084080/ef1dd2e2-0f56-11e5-8624-741d8973e4ff.PNG)

**Comment by jduggan1** [comment]
Thank you for finding this. It seems I need to separate my lexical search into two files (one for common, one for latin). That should be a simple, but tedious, change (I will try to finish it Monday or Tuesday this week).

**Comment by jduggan1** [comment]
Ok, I just pushed up a patch which should improve this considerably.  Could you all test the lexical search out and let me know if you still have problems?

**Comment by tpcolson** [comment]
How are the lists generated, and why tedious? What will happened when we do a new "extract" which may render the current two lists obsolete? Is there a way to auto-generate the lists? Would this be solved if we were using CartoDB SQL Database as the source, instead of a static text file?

**Comment by jduggan1** [comment]
Ah, sorry I should've explained better.  Those lists get produced on the supercomputer, but I needed to do a bit of work to get the relevant script for the supercomputer set up to do this.  Now that's it's done (assuming the results look better now) this should be a non-issue, as @lonnieljyu should run the scripts to produce these files when producing the habitat models as new extracts roll in. :-)

**Comment by jduggan1** [comment]
I believe this is an issue from the old site that I missed earlier.
