### ISSUE TITLE
View Observed sightings is not intuitive

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#39]
View Observed sightings should be able to turned on and off in both the first toolbar, as well as the "Search" toolbar. Having to go back to the first toolbar to turn them on or off is confusing, given our target audience.

**Comment by jduggan1** [comment]
I will ask Sarah about fitting this into the search portion of the tophat.

**Comment by jduggan1** [comment]
Missed this one last night. Should be gone with the updated site.
