### ISSUE TITLE
COMPARE WITH ...SPECIES WITH SIMILAR DISTRIBUTION: Clear results

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#42]
In COMPARE WITH ...SPECIES WITH SIMILAR DISTRIBUTION, should be able to clear/null values in the species 1 and 2 drop lists.

**Comment by jduggan1** [comment]
I'll ask Sarah about putting in a clear species button next to each dropdown.

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
