### ISSUE TITLE
COMPARE WITH ...SPECIES WITH SIMILAR DISTRIBUTION: Show observations is wonky

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#43]
COMPARE WITH ...SPECIES WITH SIMILAR DISTRIBUTION: Show observations is wonky when there are 3 species distros in effect. To be honest, trying to show 3 different observation geojsons will always be confusing. Would rather have show geojsons disabled when more than one species is being shown, or, add more buttons or something to be able to cycle thru and only show one of three species geojsons at a time, based on when species are present in the picklists.

**Comment by jduggan1** [comment]
I agree with you, but I'm not quite sure how to handle this. Let me give this some thought and I'll get back to you.

**Comment by jduggan1** [comment]
Observations should be disabled when showing more than 1 species now.
