### ISSUE TITLE
COMPARE WITH ...SPECIES WITH SIMILAR DISTRIBUTION: Change order of layers

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#46]
COMPARE WITH ...SPECIES WITH SIMILAR DISTRIBUTION...should be able to re-order what layer is on top of what layer, suggest using the color legend to be able to reorder the layering of species 1-3.

**Comment by jduggan1** [comment]
Yes, I need to go back and make some improvements Sarah suggested to that. I have an issue to do that, so I'm marking this as a duplicate.

**Comment by jduggan1** [comment]
This is present in the updated site. You can drag and drop the handles in the top left of each color legend row to re-order.
