### ISSUE TITLE
Species 1, 2, and 3: Labeling is confusing. 

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#48]
In all of the search functions, the picklists are labeled "Species 1" and "Species 2", however, when related to the color legend, these are in fact "Species 2" and "Species 3". All picklist labels should be "Species 2" and "Species 3".

**Comment by KendraStraub** [comment]
Can we update the legend verbiage from "Species 1" etc to displaying the actual species name to avoid confusion?

**Comment by KendraStraub** [comment]
I see what you are saying TC-- The search functions still show "Species 1" and "Species 2" even when you have already chosen a species 1. This is confusing.

**Comment by jduggan1** [comment]
Good point, I've made this change.
