### ISSUE TITLE
Compare with another species in park allows unlimited species but 1 geojson

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#49]
Compare with another species in park allows unlimited species but 1 geojson to be shown. When a single species is shown in the first search function, then "comparing" to any number of another species in the park, AND, show obs was enabled for the first species, the geojson for just the first species persists. Recommend compare to other species in park be limited to 3 species total, see other issue about controlling how geojson visibilty can be controlled by user.

**Comment by KendraStraub** [comment]
It is unclear to me whether any of the distributions are showing up on the map when I interact with this search functionality. 

Should function in the same manner as the COMPARE WITH.... Species with similar distribution in which the species you choose are clearly displayed in the selection bars. 

![8](https://cloud.githubusercontent.com/assets/8036575/8084419/e6e58b18-0f58-11e5-907a-270a0cc3276e.PNG)

**Comment by jduggan1** [comment]
I need to redo the lexical comparison, this should be resolved once I fixed that (thus I'm marking it as a duplicate). I'll leave this open as a reminder to come back and verify this once I'm done with that.

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
