### ISSUE TITLE
COMPARE WITH... Species with similar environment

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#50]
No species drop down list appears when I toggle to this search functionality. There is just black space 
next to the radio button selection. 

![capture](https://cloud.githubusercontent.com/assets/8036575/8083809/483a0136-0f55-11e5-826d-392e2ba8e670.PNG)

**Comment by jduggan1** [comment]
Sorry for all of the comments like this, but could you check this one again with the latest version?

**Comment by KendraStraub** [comment]
I have been using this URL: 
http://seelab.eecs.utk.edu/species_mapper/

Is this the most current?

If so I still see the same issue. 
![1](https://cloud.githubusercontent.com/assets/8036575/8546275/5e6cf5dc-2484-11e5-891a-c9bae45c7361.PNG)

**Comment by jduggan1** [comment]
I still have no idea what's going on here.  I've tried searching with the same species and it doesn't do this on my end.  Would you be willing to view your console for me (on Chrome it's Ctrl + Shift + J), and
post any errors listed there?

**Comment by KendraStraub** [comment]
Hi John-- when I tried it again I got the same results as in my last comment. Nothing appears in the "Species with Similar Environment" area. 

Here is the info from my console:
http://seelab.eecs.utk.edu/common/commonspot/templates/images/controls/lightbox.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://seelab.eecs.utk.edu/common/commonspot/templates/images/bullets/brown.gif Failed to load resource: the server responded with a status of 404 (Not Found)
http://seelab.eecs.utk.edu/common/commonspot/templates/images/graphics/loader.gif Failed to load resource: the server responded with a status of 404 (Not Found)
http://seelab.eecs.utk.edu/common/commonspot/templates/images/lightbox/loading_background.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://seelab.eecs.utk.edu/common/commonspot/templates/images/lightbox/overlay.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://seelab.eecs.utk.edu/species_mapper/templates/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://b.tiles.mapbox.com/v4/nps.GRSM_0000223_blue/10/275/404.png?access_token=pk.eyJ1IjoibnBzIiwiYSI6IkdfeS1OY1UifQ.K8Qn5ojTw4RV1GwBlsci-Q Failed to load resource: the server responded with a status of 404 (Not Found)
http://b.tiles.mapbox.com/v4/nps.GRSM_0000223_blue/10/273/402.png?access_token=pk.eyJ1IjoibnBzIiwiYSI6IkdfeS1OY1UifQ.K8Qn5ojTw4RV1GwBlsci-Q Failed to load resource: the server responded with a status of 404 (Not Found)
searchTool.js:1893 Uncaught TypeError: Cannot read property 'Ablabesmyia_mallochi' of undefined

**Comment by jduggan1** [comment]
That last line tells me what the problem is, the environment comparison data is taking too long to load.  I think if I disable the controls until all resources are loaded, it will fix this.  Let me see what I can do.  :-)

**Comment by jduggan1** [comment]
Kendra, can you check if you are still having this issue?  My latest change to the site should take care of this (though, the toolbar might take a bit longer before you can use it).

**Comment by KendraStraub** [comment]
Works perfectly now-- thanks John!

![image](https://cloud.githubusercontent.com/assets/8036575/9365455/aa042908-467f-11e5-97ae-01651c4d4615.png)
