### ISSUE TITLE
COMPARE WITH... Species with similar environment> COMPARE WITH... Another species in the park

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#51]
Toggle verbiage overlaps

![2](https://cloud.githubusercontent.com/assets/8036575/8083960/3223ae5a-0f56-11e5-9b29-1812b8074f99.PNG)

**Comment by jduggan1** [comment]
Woah, what browser&version are you using? I probably need to use something like BrowserStack to go through the site on a list of browsers/versions as it is but for now I'll stick to fixing it for yours. :-)

**Comment by KendraStraub** [comment]
I am using Chrome Version 43.0.2357.124 m (64-bit)

**Comment by jduggan1** [comment]
Can you check if this is fixed in the latest version?  It's a bit hard to tell from the screenshot if it's the same one I found and fixed earlier, but it seems to be.

**Comment by KendraStraub** [comment]
I cannot reproduce the error-- SO it appears to be resolved.
