### ISSUE TITLE
COMPARE WITH... Another species in the park: Compare Against Same Species?

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#52]
Should a user be able to compare a species with itself? I think that if a species is chosen in the original search it should be excluded from subsequent searches. 

![7](https://cloud.githubusercontent.com/assets/8036575/8084342/812e7eb0-0f58-11e5-8ec7-2302207ead24.PNG)

**Comment by jduggan1** [comment]
I need to redo the lexical comparison already (at which point this won't be a problem anymore), so I'm marking this as a duplicate. I'll come back and close this once I've finished the original issue related to this.

**Comment by jduggan1** [comment]
I've been thinking a bit about this in the past few days, and I'm reluctant to fix this specific portion of the lexical search.  While it may not make much sense for a user to type in and choose the same species they are currently looking at, I think it would be confusing for a user to search for the species a second time and not have it show up (who knows, maybe they really want to see the species in multiple colors).

However, I will defer to you all, so let me know what you think and I'll update this accordingly.

**Comment by jduggan1** [comment]
This should be fully resolved with my latest commit.
