### ISSUE TITLE
Tooltips/ Hover/Pop-up Context/Instructions/Explanation

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#53]
In general, I think the site needs a lot of explanation/context through multiple avenues. It presents some very complex material and I think interpretation is limited without robust explanation. I am not sure how to best design and integrate this, I suppose Sarah would need to make that call. 

I think every single search option (e.g., Species with similar environment) needs at least a paragraph of explanation. Perhaps the title could be a link and when the link is clicked it could open a pop-up with some detail, What do we mean by "similar environment"?; What are some examples of environmental parameters we used in this modelling effort?; How can I judge how similar the their environment really is? Is there some cutoff of similarity after which they are no longer considered similar? I even think that we should explain the order in which the species show up in the species search bar-- most similar to least similar.

**Comment by jduggan1** [comment]
I've added tooltips and help for as many parts of the tool as I can think of. I'll leave this open for now, but feel free to close this if you all are satisfied.

**Comment by KendraStraub** [comment]
resolved.
