### ISSUE TITLE
Drop down list needs to close when toggling to different search type

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#56]
I noticed that when I toggled from Compare Area to Compare Distribution, the drop down from compare area stayed open. This looked confusing and messy. 
![4](https://cloud.githubusercontent.com/assets/8036575/8546471/1aebc034-2486-11e5-942e-99ee48975724.PNG)

**Comment by KendraStraub** [comment]
Upon further testing I have found that the drop down list is locked in the open position, and no matter where I toggle it does not close.

**Comment by jduggan1** [comment]
Sorry about that, I introduced that yesterday fixing an issue with the dropdown boxes.  Should be fixed now.  :-)
