### ISSUE TITLE
Shelters

### ISSUE THREAD

**Issue by jduggan1** [nationalparkservice/npmap-species#59]
@tpcolson: it looks as though the shelters link is broken.  Could you confirm and if necessary provide a new link?

**Comment by tpcolson** [comment]
http://services1.arcgis.com/fBc8EJBxQRMcHlei/ArcGIS/rest/services/GRSM_BACKCOUNTRY_SHELTERS/FeatureServer/0/query?f=geojson&outSR=4326&where=OBJECTID%20IS%20NOT%20NULL&outFields=* seems to be working....?

**Comment by jduggan1** [comment]
Thanks!  I've updated the site and it looks good.
