### ISSUE TITLE
Resize search pane on window resize

### ISSUE THREAD

**Issue by jduggan1** [nationalparkservice/npmap-species#6]
The search pane currently does not resize when the window resizes, causing strange behavior.  Need to set up an on resize function (fullscreen in/out already provides the functionality needed).

**Comment by KendraStraub** [comment]
When in default zoom, latin/common toggle falls outside screen area. When zoom out, toggle is still out of accordion area. 
![6](https://cloud.githubusercontent.com/assets/8036575/8084219/e4e1e4c0-0f57-11e5-9cd7-f737d55781be.PNG)

**Comment by jduggan1** [comment]
Kendra, what browser and what version of it are you using? I haven't seen this happen before (plus the close dialog in the top right corner looks odd).

**Comment by KendraStraub** [comment]
I am using Chrome Version 43.0.2357.124 m (64-bit)

**Comment by jduggan1** [comment]
This issue is gone with the updated site.
