### ISSUE TITLE
Observation Information

### ISSUE THREAD

**Issue by TomRemaley** [nationalparkservice/npmap-species#62]
When an observation point is clicked it should display common name, scientific name, coordinates and date

**Comment by jduggan1** [comment]
Tom, I don't think we have dates of the observations in the ATBI records, but I've updated the information to include the other aspects you mentioned above.

**Comment by tpcolson** [comment]
This is waiting on another "Extract"

**Comment by jduggan1** [comment]
I'm able to get the date from CartoDB, but unable to convert from epoch time in milliseconds to a date string using the current dateFormat helper for Handlebars.

**Comment by jduggan1** [comment]
I have added date conversion with https://github.com/nationalparkservice/npmap-species/commit/97adb8150afc4d333eb6b144d8995363031f7c6b. It's a hack, but it should get the job done for now. With this, the observation popups should be complete now.
