### ISSUE TITLE
Legend: Percentages

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#63]
Points to need to more explanation of the various aspects of the species mapper. 

Commenter: Joshua Albritton, GRSM biotech
"For a given species distribution, what do the percent ranges on the legend equate to? a confidence interval of sorts for likelihood of occurrence?"

**Comment by tpcolson** [comment]
Add pop-up mouse over which explains what the percentages mean to the legend box.

**Comment by jduggan1** [comment]
I've added a tooltip for the percentages with https://github.com/nationalparkservice/npmap-species/commit/72f8aba9b15843078068db4b6ce6c913ad47b335.
