### ISSUE TITLE
Predicted Species: Color

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#64]
Commenter: Joshua Albritton, GRSM biotech

"The blue colors on the primary species distribution can perhaps get mixed up with the water layer, especially if you're zoomed out a little and using terrain map-dark or if the distribution is limited and at low elevations (e.g., Acer negundo). Not a big deal, but maybe consider it"
![1](https://cloud.githubusercontent.com/assets/8036575/10225428/d50b055e-6830-11e5-877d-a896f4c5fb9d.PNG)

**Comment by jduggan1** [comment]
Update: We've got a new set of colors (056c58 / 1d909b / 60c8d1), but are needing to get an issue fixed on the machine running TileMill before we can push the change to mapbox.
