### ISSUE TITLE
Compare with species with similar environment: Context/Explanation

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#65]
Commenter: Joshua Albritton, GRSM biotech

"When comparing species with another species based on similar environment, how is that query generated? I had some interesting comparisons when for example I compared Fraser fir. Some on the comparison list included Juglans, Ulmus and Acer negundo, but did not include what I may have expected such as spruce or yellow birch."

**Comment by jduggan1** [comment]
Since we are removing this portion of the tool, I'm closing this issue.
