### ISSUE TITLE
Select Time Period and Compare

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#67]
Commenter: Keith Langdon, former GRSM I&M program coordinator

"big landscape changes since park establishment and recently with great losses of trees and other species makes one wish to be able to select the time period and compare (as with 2 species in your excellent current feature).  Otherwise the accuracy of the modeling will get "muddled". Not essential now, but with more legacy data coming in, climate change in future, it'll be needed."

**Comment by KendraStraub** [comment]
@TomRemaley - do you agree with this feature request? It doesn't seem like our data meet the assumptions that this visualization would infer.

**Comment by tpcolson** [comment]
With the proposed introduction of the BioClim data to the environmental variables, this stands as a valid request.
