### ISSUE TITLE
Data Quality Reversed?

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#68]
Commenter: Keith Langdon, former GRSM I&M program coordinator

"the "Data Quality" in lower right corner is reversed...e.g. red maple with ~4,000 points is "Poor" and  species with 30+ points only are "Excellent". Since almost all our data is excellent quality...maybe this index should say "Current Model Confidence" or something similar?"

![2](https://cloud.githubusercontent.com/assets/8036575/10225782/52b65124-6832-11e5-9592-06f81864a905.PNG)

**Comment by lonnieljyu** [comment]
@KendraStraub: The Area Under the Curve (AUC) value calculated by Maxent for acer_rubrum_v_rubrum is 0.6924, meaning the test samples we have of the species are almost as bad as a random prediction (random prediction AUC = 0.5). Having more observation points does not necessary mean a better AUC value.

You can read more about calculating AUC in Maxent here: http://www.cs.princeton.edu/~schapire/maxent/tutorial/tutorial.doc

**Comment by KendraStraub** [comment]
Thanks for the background @lonnieljyu

I guess we need to come up with a way to convey these things to the end users as well.

**Comment by lonnieljyu** [comment]
@KendraStraub: we'll be putting in tooltips and help sections to explain the interface and terminology.

**Comment by jduggan1** [comment]
Not sure why this was closed. Sarah and I will need to work on populating the help/tooltips further, and I'd like to make sure this feedback isn't missed.

**Comment by KendraStraub** [comment]
@jduggan1  I think changing the phrase from "Data Quality" to "Model Confidence" helps clear this up a bit-- but the tooltips will provide further context and explanation.

**Comment by jduggan1** [comment]
I've added a tooltip for the model confidence sections with https://github.com/nationalparkservice/npmap-species/commit/72f8aba9b15843078068db4b6ce6c913ad47b335.
