### ISSUE TITLE
Auto-correlation between similar distribution and similar environment?

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#70]
May just be need for further context/explanation on the site. But user would also like to see environmental layers in the interface.

Commenter: Keith Langdon, former GRSM I&M program coordinator

"Standard comparisons: I like the comparisons, but thinking on it, aren't the  species with similar distribution and species with similar environment "auto-correlated" to significant degree?  I think I would find a list of GIS layers much more helpful, i.e., geology bedrock, soil pH in A horizon, solar aspect, elevation, avg temperature in July, topographical shading, etc, etc."

**Comment by jduggan1** [comment]
I'm closing this as we are removing the similar environment option.
