### ISSUE TITLE
Unable to change species selection 

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#72]
I tested this and got the same results as Keith. 

Commenter: Keith Langdon, former GRSM I&M program coordinator

"There appears to be a glitch at the Spring salamander Gyrinophilus porphyriticus.  I have examined about 15% of the species models, but when I go to this taxon, it sticks.  You cannot select another species.  I tried this over a couple days, entering by both common name and Latin and the only way I could get out was to shut down the site.... and then go back in.  Whatever is wrong with it, you may want to examine the other species models as well, since I have not looked at the majority of them."

**Comment by tpcolson** [comment]
I cannot reproduce this, what browser/version is this in?

**Comment by KendraStraub** [comment]
@tpcolson - Chrome. Try with the species mentioned. John is aware of the issue and it will be resolved when he runs the model again. The issue only occurred with species newly added to the last extract,.

**Comment by KendraStraub** [comment]
Resolved.
