### ISSUE TITLE
Species pick list font is too small

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#75]
Species pick list font is too small and like does not meet NPS 508 requirements. Seems like there is some room to bump up the font size. 

![image](https://cloud.githubusercontent.com/assets/5861784/10481806/4b79b8b0-7241-11e5-8a3e-a3210e924071.png)

**Comment by jduggan1** [comment]
Tom, I increased all font sizes to at least 10pt. Will this be sufficient?

**Comment by KendraStraub** [comment]
@tpcolson  -- Is the font big enough?

**Comment by tpcolson** [comment]
There is nothing on http://imtest/im/examples/text.cfm#paragraph about legal font size

**Comment by jduggan1** [comment]
In that case, I'm going to close the issue since I've increased the font sizes. We can revisit this if needed once testing begins.
