### ISSUE TITLE
NPS Logo only appears in chrome

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#78]
NPS Logo only appears in chrome

![image](https://cloud.githubusercontent.com/assets/5861784/10482003/b2f131e8-7242-11e5-91b6-6a20dd04f79c.png)

![image](https://cloud.githubusercontent.com/assets/5861784/10482010/bc4d7a3a-7242-11e5-9535-7d95f3acab96.png)

**Comment by jduggan1** [comment]
@tpcolson: is this IE 9?

**Comment by jduggan1** [comment]
@tpcolson: I spent some time and I think I've fixed the issue with the image (and a few other issues on Internet Explorer). Are you still seeing these issues?

**Comment by KendraStraub** [comment]
@jduggan1 FYI this issue still seems to be occurring in IE.

![capture](https://cloud.githubusercontent.com/assets/8036575/10920795/22bd5134-8240-11e5-828c-ac7476163b28.PNG)

**Comment by jduggan1** [comment]
The problems mentioned here should be fixed as of today. Let me know if you're still seeing any issues on IE.
