### ISSUE TITLE
Most similar species aren't always similar

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#80]
Seems to be some confusion over this functionality. This may be resolved by context/explanation.

Commenter: Becky Nichols, GRSM Entomologist

"I selected northern copperhead (this distribution doesn't look accurate), and then selected the American strawberry-bush as a comparison with a "species with similar distribution." They don't look similar."

She also commented:
"It's not clear what "compare with species with similar environment" means. "

**Comment by jduggan1** [comment]
No worries about the similar environment issue any more, but the part regarding ensuring that we only show species that are truly similar is still relevant.

**Comment by jduggan1** [comment]
I've added functionality for pruning the similar distribution lists. Species that are below a given threshold of similarity are ignored now.
