### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#81]
Commenter: Becky Nichols, GRSM Entomologist

"Zoom function seems course. "

**Comment by jduggan1** [comment]
Is this referring to a desire for a higher maximum level of zoom, less drastic changes between the zoom levels, or something else? I have control over the maximum zoom level, but not much else.

**Comment by KendraStraub** [comment]
I confirmed with Becky that this refers to the drastic changes between zoom
levels.

On Wed, Oct 21, 2015 at 3:17 PM, John Duggan <notifications@github.com>
wrote:

> Is this referring to a desire for a higher maximum level of zoom, less
> drastic changes between the zoom levels, or something else? I have control
> over the maximum zoom level, but not much else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-species/issues/81#issuecomment-149998427>
> .
>



-- 
*Kendra Straub*
*Data Manager*
Great Smoky Mountains National Park
Gatlinburg, TN
865.436.1703
DM/GIS Sharepoint site
<http://share.inside.nps.gov/sites/GRSM/rms/gisdata/default.aspx>

**Comment by jduggan1** [comment]
I was afraid of that. To my knowledge, I am unable to control the changes between the zoom levels.

**Comment by KendraStraub** [comment]
Okay, good to know. TC-- is this something you can run up the chain?
Perhaps just making "them" aware of this enhancement request?

On Thu, Oct 22, 2015 at 11:36 AM, John Duggan <notifications@github.com>
wrote:

> I was afraid of that. To my knowledge, I am unable to control the changes
> between the zoom levels.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/npmap-species/issues/81#issuecomment-150264851>
> .
>



-- 
*Kendra Straub*
*Data Manager*
Great Smoky Mountains National Park
Gatlinburg, TN
865.436.1703
DM/GIS Sharepoint site
<http://share.inside.nps.gov/sites/GRSM/rms/gisdata/default.aspx>

**Comment by tpcolson** [comment]
This is something that comes from the way Mapbox structures the tiling scheme and zoom levels, and unfortunately, I don't think something they're going to change any time soon. We do have the option of hosting our own tile server to get around this, at great expense. Mapbox tile schemes are meant to provide smooth zoom levels for the whole country, and don't favor the park footprint.
