### ISSUE TITLE
Common name confusion

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#82]
End user was confused by the many "unspecified" entries on the species drop-down when she toggled to common. We will never be able to assign common names to all of the species so I wonder if there is anything in the design/context that can help clarify this for people. 

Commenter: Becky Nichols, GRSM Entomologist

"What does "unspecified" mean as a species selection? A distribution shows up, but you you don't know what it is."

**Comment by jduggan1** [comment]
I've removed the Unspecified species from the selectors when using common name mode. Once a species is selected, the user can switch to common name mode and see the Unspecified name for a selected species.
