### ISSUE TITLE
Draw on Map Bug?

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#83]
Commenter: Becky Nichols, GRSM Entomologist

"The "dot" selection in the "draw on map" window doesn't always work. I selected the dot, clicked on the map, and sometimes a dot would appear, sometimes not. Also, the dot is different sizes sometimes."

**Comment by jduggan1** [comment]
Is this referring to the circle drawing tool (the right-most button of the three)? I probably need to do a better job with tooltips and the help overlay of explaining what each of these tools is for.

**Comment by KendraStraub** [comment]
This comment refers to the circle drawing tool. I clarified with her. She did not know you have to click and drag to create a circle in the size of your choosing. She was just clicking the tool and then clicking the map. If you do that sometimes a small circle will be created, but many times no circle is created.

**Comment by tpcolson** [comment]
Add a pop up for a mouse-over for each of the drawing tools to briefly explain how to use and what the result is.

**Comment by jduggan1** [comment]
I've added the tooltips to the drawing tools. In the case of the circle, the tooltip specifically mentions to click *and* drag. Hopefully this removes confusion for users during the next round of testing.
