### ISSUE TITLE
Size of page

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#85]
Commentor: 20 something GRSM intern

"The webpage window is too large for my screen. Even when I make my browser full-screen, I have to scroll laterally to use buttons on the edges of the page. I tried this in Chrome and Internet Explorer - no change."

--> He had to scroll horizontally to see all of the annotation tools. 

![capture_speciesmapper](https://cloud.githubusercontent.com/assets/8036575/10982794/618c2f22-83dd-11e5-93fe-3620378d3426.PNG)

**Comment by jduggan1** [comment]
Kendra, this monitor appears to be 1280x1024 resolution, while our tool is 1366 pixels wide. These monitors are so rare at this point in time that it wouldn't be worth it to re-design just to prevent having to scroll to access a few of the tools. Here's more information if you're interested: http://www.w3schools.com/browsers/browsers_display.asp
