### ISSUE TITLE
Grouping Request

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#86]
Commentor: 20 something GRSM intern

"I think it would be helpful to have the option to sort the species drop-down list by flora and fauna."

**Comment by tpcolson** [comment]
We are looking more closely at this, and want to expand grouping combined with influence of environmental variable on endemicity

**Comment by KendraStraub** [comment]
Closing this. Grouping is part of this phase. This specific grouping request will be met in that development.
