### ISSUE TITLE
Symbology Hard to Distinguish

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#87]
Commentor: 20 something GRSM intern

"The campsites, trails and shelters are all symbolized with the same yellow hue.  Although the actual symbols are different, I find that it's hard to distinguish between them when all three are present on the map.  "

**Comment by tpcolson** [comment]
For shelters, use the following, assuming you're using NPMAP JS:

      "styles": {
        "point": {
          "marker-library": "npmapsymbollibrary",
          "marker-symbol": "shelter-white",
          "marker-color": "#000000",
          "marker-size": "medium"
        }
      }

**Comment by tpcolson** [comment]
For Visitor centers use: 

      "styles": {
      "styles": {
        "point": {
          "marker-library": "npmapsymbollibrary",
          "marker-symbol": "visitor-center-white",
          "marker-color": "#000000",
          "marker-size": "medium"
        }
      }

**Comment by tpcolson** [comment]
For campsites use 
      "styles": {
        "point": {
          "marker-library": "npmapsymbollibrary",
          "marker-symbol": "campsite-white",
          "marker-color": "#000000",
          "marker-size": "medium"
        }
      }

**Comment by tpcolson** [comment]
![image](https://cloud.githubusercontent.com/assets/5861784/12275902/b3b49b2a-b940-11e5-848f-4a0980247d8a.png)
![image](https://cloud.githubusercontent.com/assets/5861784/12275910/c07f3f18-b940-11e5-8aea-adb484d0d850.png)
![image](https://cloud.githubusercontent.com/assets/5861784/12275922/ca7e8e42-b940-11e5-8cb9-8a724c173749.png)

**Comment by tpcolson** [comment]
https://github.com/nationalparkservice/npmap-symbol-library

**Comment by jduggan1** [comment]
![overlays](https://cloud.githubusercontent.com/assets/8481770/12277723/0002669c-b94b-11e5-8d3e-0bbe313e4876.png)

**Comment by jduggan1** [comment]
I've made the changes. The above image has all of the overlays together. If you're happy, feel free to close it; otherwise, I'll probably do so in a few days if I don't hear anything about changing it further.
