### ISSUE TITLE
Compare with Another Species

### ISSUE THREAD

**Issue by TomRemaley** [nationalparkservice/npmap-species#88]
Need to have a drop down menu of species with option to type

![capture](https://cloud.githubusercontent.com/assets/8590071/11505038/4bd49c58-9816-11e5-86f9-b3b47eb01755.JPG)

**Comment by jduggan1** [comment]
Done with https://github.com/nationalparkservice/npmap-species/commit/c9228fbfb429041b7c6c76e7a61754ed444ad99a. These dropdowns should behave exactly like the initial dropdown.
