### ISSUE TITLE
Data Quality text...

### ISSUE THREAD

**Issue by TomRemaley** [nationalparkservice/npmap-species#89]
should be changed to "Model Confidence"

![capture1](https://cloud.githubusercontent.com/assets/8590071/11505077/94131062-9816-11e5-923f-b5d8644f4973.JPG)

**Comment by jduggan1** [comment]
This change has been made with commit https://github.com/nationalparkservice/npmap-species/commit/40e0fca311755e2233a769ac64ae0670a836bf0d
