### ISSUE TITLE
Pop-Ups

### ISSUE THREAD

**Issue by TomRemaley** [nationalparkservice/npmap-species#90]
[Pop-Ups.docx](https://github.com/nationalparkservice/npmap-species/files/87233/Pop-Ups.docx)

**Comment by tpcolson** [comment]
What is GRSM Species Mapper:

The GRSM Species Mapper uses “presence-only” methods to create models to predict suitable habitat where plants and animals live in the park. These models are based on data collected from current and legacy monitoring and research activities and combinations of environmental (slope, forests types, geology, elevation, etc.) and climate variables (temperature, sun exposure, etc.). The models are meant to give a reliable idea where each species occurs in the park. As additional field observations of each species accrue they are added to the model to increases its accuracy.


Compare with…

●	Another Species in the Park
	Select another species that is known to exist in the park.
●	Species with Similar Distribution
	Select another species with similar habitat requirements across the park.

**Comment by jduggan1** [comment]
Added with https://github.com/nationalparkservice/npmap-species/commit/dac37c946448e64c4aa96459617efa13945baccf.
