### ISSUE TITLE
Polygon appears under cluster icons

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#96]
With the observations turned on, and clustered, on mouse over, a polygon appears under the clusters? ????

![image](https://cloud.githubusercontent.com/assets/5861784/12277575/1346fa48-b94a-11e5-9b42-b075fc171e4c.png)

**Comment by jduggan1** [comment]
That's actually a feature of the marker cluster library. The polygon represents the area covered by the observations within a cluster. I can turn it off if you would like. :-)

**Comment by jduggan1** [comment]
@tpcolson: Do you want me to remove the polygons? This one will take me 5 minutes to close whether you want me to remove or keep it, and it'd be nice to get it out of the tracker.

**Comment by tpcolson** [comment]
let's remove it, it can be confusing to those that don't think in terms of GIS

**Comment by jduggan1** [comment]
Done with https://github.com/nationalparkservice/npmap-species/commit/01307c00ae28c46de36cdc9a666d2f2b2f63f355
